# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  base_port = 8080
  { 'centos/7' => 'centos-apache', 'ubuntu/bionic64' => 'ubuntu-apache' }.each do |box, hostname|
    config.vm.define hostname do |machine|
      machine.vm.box = box
      machine.vm.hostname = hostname
      machine.vm.network "forwarded_port", guest: 80, host: base_port
      base_port+=1
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
     ansible.groups = {
      "webservers" => ["ubuntu-apache", "centos-apache"]
     }
  end
end
