#!/bin/bash

set -eo pipefail

TEMPFILE=$(mktemp /tmp/vag2ansible.XXXXXX)
vagrant ssh-config > $TEMPFILE

echo -e "all:\n  vars:\n    ansible_ssh_host: 127.0.0.1\n    ansible_ssh_user: vagrant\n  hosts:"
cat $TEMPFILE |  egrep "(Host|Port|IdentityFile) " | sed -r 's@/.*(/\.vagrant/.*)@.\1@;s/^ +//;s/^Host (.*)/    \1:/;s/^Port (.*)/      ansible_ssh_port: \1/;s/^IdentityFile (.*)/      ansible_ssh_private_key_file: \1/'
echo "  children:"
echo -e "    pares:\n      hosts:"
for host in $(grep "Host node-" $TEMPFILE | sed 's/Host //'); do
  if ! (( $(echo $host | sed 's/node-//') % 2 )); then
  echo "        $host:"
  fi
done
echo -e "    impares:\n      hosts:"
for host in $(grep "Host node-" $TEMPFILE | sed 's/Host //'); do
  if (( $(echo $host | sed 's/node-//') % 2 )); then
  echo "        $host:"
  fi
done

rm -f $TEMPFILE
