# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  1.upto(6) do |number|
    vmname = "node-#{"%02d" % number}"
    config.vm.define vmname do |instance|
      instance.vm.box = "ubuntu/bionic64"
      instance.vm.hostname = vmname
    end
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end
end
